language: cpp
compiler:
  - gcc
before_install:
  - sudo apt-get update
  - sudo apt-get install -y cmake libsdl-ttf2.0-dev libsdl-mixer1.2-dev libsdl-image1.2-dev libboost-all-dev
script:
  - mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=../dist .. && make install && cd ..

